name: CI Workflow  # optional workflow name

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check CLIENT_SECRET
        run: |
          if [ -z "${{ secrets.CLIENT_SECRET }}" ]; then
            echo "CLIENT_SECRET is not set. Failing the job."
            exit 1
          else
            echo "CLIENT_SECRET is set."
          fi
