name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check CLIENT_SECRET
        run: |
          if [ -z "${{ secrets.CLIENT_SECRET }}" ]; then
            echo "CLIENT_SECRET is not set. Failing the job."
            exit 1
          else
            echo "CLIENT_SECRET is set."
          fi

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: luciafbrown/project-backend:latest
